/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablex2 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2) NULL,
    CONSTRAINT pk_tablex2 PRIMARY KEY (id)
);
