/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tabley2 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT pk_tabley2 PRIMARY KEY (id)
);
