/*
[RayMigrator]
Description = "Create initial model"
UseTransaction = false
*/

CREATE TABLE Person
(
 Id INT AUTO_INCREMENT NOT NULL,
 LoginId INT NOT NULL,
 SexId TINYINT NOT NULL,
 NameFirst VARCHAR(100) NOT NULL,
 NameLast VARCHAR(100) NOT NULL,
 DateOfBirth DATE NULL,
 CONSTRAINT PK_Person PRIMARY KEY (Id)
) ENGINE=InnoDB;

CREATE TABLE Sex
(
 Id TINYINT NOT NULL,
 Name VARCHAR(100) NOT NULL,
 CONSTRAINT PK_Sex PRIMARY KEY (Id)
) ENGINE=InnoDB;

CREATE TABLE Login
(
 Id INT AUTO_INCREMENT NOT NULL,
 Username VARCHAR(100) NOT NULL,
 PasswordHash VARCHAR(256) NOT NULL,
 LastLogin DATETIME(2) NULL,
 CONSTRAINT PK_Login PRIMARY KEY (Id)
) ENGINE=InnoDB;

ALTER TABLE Person ADD CONSTRAINT Sex_Person FOREIGN KEY (SexId) REFERENCES Sex (Id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Person ADD CONSTRAINT Login_Person FOREIGN KEY (LoginId) REFERENCES Login (Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
