/*
[RayMigrator]
Description = "Create TableA"
*/

CREATE TABLE tablea (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tablea PRIMARY KEY (id)
);
