/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tableg (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(50) NOT NULL,
    status INT NOT NULL DEFAULT 0,
    CONSTRAINT pk_tableg PRIMARY KEY (id)
);
