/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tableh (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category VARCHAR(100) NOT NULL,
    weight DECIMAL(10,2) NULL,
    CONSTRAINT pk_tableh PRIMARY KEY (id)
);
