/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablec (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2) NULL,
    CONSTRAINT pk_tablec PRIMARY KEY (id)
);
