/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tabled (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50) NOT NULL,
    description TEXT NULL,
    CONSTRAINT pk_tabled PRIMARY KEY (id)
);
