/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablex4 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(50) NOT NULL,
    status INT NOT NULL DEFAULT 0,
    CONSTRAINT pk_tablex4 PRIMARY KEY (id)
);
