/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tabley4 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category VARCHAR(100) NOT NULL,
    score DECIMAL(10,2) NULL,
    CONSTRAINT pk_tabley4 PRIMARY KEY (id)
);
