CREATE TABLE IF NOT EXISTS inheritancemarker_alpha
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    markername VARCHAR(100) NOT NULL,
    CONSTRAINT pk_inheritancemarker_alpha PRIMARY KEY (id)
);

INSERT INTO inheritancemarker_alpha (markername) VALUES ('R1.0_Alpha');
