/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablex1 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT pk_tablex1 PRIMARY KEY (id)
);
