/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tabley1 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description TEXT NULL,
    weight DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    CONSTRAINT pk_tabley1 PRIMARY KEY (id)
);
