/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablee (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ref VARCHAR(50) NOT NULL,
    data TEXT NULL,
    CONSTRAINT pk_tablee PRIMARY KEY (id)
);
