/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablef (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag VARCHAR(50) NOT NULL,
    priority INT NULL,
    CONSTRAINT pk_tablef PRIMARY KEY (id)
);
