using System.Text;
using System.Text.RegularExpressions;
using Raycoon.RayMigrator.ConfigWizard.Core.Models;

namespace Raycoon.RayMigrator.ConfigWizard.Core.Services;

/// <summary>
/// Generates example.env file content listing all {ENV:} variables used in the configuration.
/// </summary>
public static class EnvFileGenerator
{
    private static readonly Regex EnvVarPattern = new(@"\{ENV:(\w+)\}", RegexOptions.Compiled);

    /// <summary>
    /// Generates a example.env file content from the configuration model.
    /// The default resolver uses <see cref="Environment.GetEnvironmentVariable(string)"/>,
    /// which is only available in environments that support it (e.g., desktop, server).
    /// Blazor WASM and other sandboxed environments should provide their own resolver
    /// via the <paramref name="envVarResolver"/> parameter to avoid platform exceptions.
    /// </summary>
    /// <param name="model">The configuration model to extract ENV variables from.</param>
    /// <param name="envVarResolver">Optional resolver for current ENV values. Defaults to Environment.GetEnvironmentVariable.</param>
    public static string Generate(ConfigurationModel model, Func<string, string?>? envVarResolver = null)
    {
        envVarResolver ??= Environment.GetEnvironmentVariable;
        var envVars = CollectEnvVariables(model);
        return FormatEnvFile(envVars, envVarResolver);
    }

    /// <summary>
    /// Generates a example.env from the exported JSON strings, scanning ALL files for {ENV:} variables.
    /// This ensures environment variables defined in env/PE files (not just the base) are included.
    /// </summary>
    public static string GenerateFromExportedJsons(
        IEnumerable<KeyValuePair<string, string>> exportedJsons,
        Func<string, string?>? envVarResolver = null)
    {
        envVarResolver ??= Environment.GetEnvironmentVariable;
        var vars = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        foreach (var (fileName, json) in exportedJsons)
        {
            foreach (Match match in EnvVarPattern.Matches(json))
            {
                var varName = match.Groups[1].Value;
                if (!vars.ContainsKey(varName))
                    vars[varName] = new List<string>();
                if (!vars[varName].Contains(fileName))
                    vars[varName].Add(fileName);
            }
        }

        return FormatEnvFile(vars, envVarResolver);
    }

    private static string FormatEnvFile(Dictionary<string, List<string>> envVars, Func<string, string?> envVarResolver)
    {
        if (envVars.Count == 0)
            return "# No environment variables used in this configuration.\n";

        var sb = new StringBuilder();
        sb.AppendLine("# RayMigrator Environment Variables");
        sb.AppendLine("# Generated by RayMigrator Config-Wizard");
        sb.AppendLine("#");
        sb.AppendLine("# Copy this file to .env and fill in the actual values.");
        sb.AppendLine();

        foreach (var (varName, usages) in envVars.OrderBy(kv => kv.Key))
        {
            sb.AppendLine($"# Used in: {string.Join(", ", usages.OrderBy(u => u, StringComparer.Ordinal))}");
            var currentValue = envVarResolver(varName);
            if (currentValue != null)
                sb.AppendLine($"{varName}={currentValue}");
            else
                sb.AppendLine($"{varName}=");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static Dictionary<string, List<string>> CollectEnvVariables(ConfigurationModel model)
    {
        var vars = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        void Track(string value, string location)
        {
            foreach (Match match in EnvVarPattern.Matches(value))
            {
                var varName = match.Groups[1].Value;
                if (!vars.ContainsKey(varName))
                    vars[varName] = new List<string>();
                if (!vars[varName].Contains(location))
                    vars[varName].Add(location);
            }
        }

        // Repository
        Track(model.Repository.ConnectionString, "Repository.ConnectionString");

        // DatabaseLogging
        if (model.DatabaseLogging != null)
            Track(model.DatabaseLogging.ConnectionString, "DatabaseLogging.ConnectionString");

        // Products
        foreach (var product in model.Products)
        {
            string pPrefix = $"Products[{product.Alias}]";
            Track(product.MigrationFilesRootDirectory, $"{pPrefix}.MigrationFilesRootDirectory");

            foreach (var tg in product.TargetGroups)
            {
                foreach (var target in tg.Targets)
                {
                    Track(target.ConnectionString, $"{pPrefix}.{tg.Alias}.{target.Alias}.ConnectionString");
                }
            }
        }

        return vars;
    }
}
