CREATE TABLE MigSettingsMarker
(
    Id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    MarkerName VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MigSettingsMarker PRIMARY KEY (Id)
);

INSERT INTO MigSettingsMarker (MarkerName) VALUES ('R1.0_Backend');
