CREATE TABLE IF NOT EXISTS inheritancemarker_beta
(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    markername VARCHAR(100) NOT NULL,
    CONSTRAINT pk_inheritancemarker_beta PRIMARY KEY (id)
);

INSERT INTO inheritancemarker_beta (markername) VALUES ('R1.0_Beta');
