/*
[RayMigrator]
Description = "Create TableB"
*/

CREATE TABLE tableb (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(200) NULL,
    CONSTRAINT pk_tableb PRIMARY KEY (id)
);
