-- TODO: Implement for your database engine
-- Purpose: Creates all repository tables (MigrationRun, MigrationRecord, MigrationRecordHistory, lookup tables) if they don't exist
-- See the corresponding template in Database.SqlServer or Database.PostgreSQL for reference.
--
-- Parameters used in this template:
-- {CFG:SchemaName} - The repository schema name
-- {CFG:TableBaseName} - The table name prefix
-- @ParameterName - SQL parameters (see reference implementations)
