PRINT '';
PRINT '### EXECUTE: 22_create_db_Backend_2.sql ###';
GO

USE [master]
GO

PRINT 'Drop existing database ...'
IF EXISTS (SELECT TOP(1) 1 FROM master.dbo.sysdatabases WHERE ([name] = 'Backend_2'))
BEGIN
	PRINT 'Drop DB [Backend_2]..'
	ALTER DATABASE [Backend_2] SET single_user WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Backend_2];
END;
GO

PRINT 'Create database [Backend_2] ...';
CREATE DATABASE [Backend_2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fg_raymigrator_primary_2', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_primary_2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
-- DATA
 FILEGROUP [fg_raymigrator_data_2]  DEFAULT
( NAME = N'fg_raymigrator_data_2', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_data_2.ndf' , SIZE = 131072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
-- INDEXES
 FILEGROUP [fg_raymigrator_index_2]
( NAME = N'fg_raymigrator_index_2', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_index_2.ndf' , SIZE = 131072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG
LOG ON 
( NAME = N'fg_raymigrator_log_2', FILENAME = N'/var/opt/mssql/log/fg_raymigrator_log_2.ldf' , SIZE = 131072KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

COLLATE Latin1_General_CI_AS
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Backend_2] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Backend_2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
SET ANSI_NULL_DFLT_ON ON 
GO
ALTER DATABASE [Backend_2] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Backend_2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Backend_2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Backend_2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Backend_2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Backend_2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Backend_2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Backend_2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Backend_2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Backend_2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Backend_2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Backend_2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Backend_2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Backend_2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Backend_2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Backend_2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Backend_2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Backend_2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Backend_2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Backend_2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Backend_2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Backend_2] SET RECOVERY FULL 
GO
ALTER DATABASE [Backend_2] SET  MULTI_USER 
GO
ALTER DATABASE [Backend_2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Backend_2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Backend_2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Backend_2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Backend_2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Backend_2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Backend_2', N'ON'
GO
ALTER DATABASE [Backend_2] SET QUERY_STORE = ON
GO
ALTER DATABASE [Backend_2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
