PRINT '';
PRINT '### EXECUTE: 23_create_db_Frontend.sql ###';
GO

USE [master]
GO

PRINT 'Drop existing database ...'
IF EXISTS (SELECT TOP(1) 1 FROM master.dbo.sysdatabases WHERE ([name] = 'Frontend'))
BEGIN
	PRINT 'Drop DB [Frontend]..'
	ALTER DATABASE [Frontend] SET single_user WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Frontend];
END;
GO

PRINT 'Create database [Frontend] ...';
CREATE DATABASE [Frontend]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fg_raymigrator_primary_3', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_primary_3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
-- DATEN
 FILEGROUP [fg_raymigrator_data_3]  DEFAULT
( NAME = N'fg_raymigrator_data_3', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_data_3.ndf' , SIZE = 131072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
-- INDEXE
 FILEGROUP [fg_raymigrator_index_3]
( NAME = N'fg_raymigrator_index_3', FILENAME = N'/var/opt/mssql/data/fg_raymigrator_index_3.ndf' , SIZE = 131072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG
LOG ON 
( NAME = N'fg_raymigrator_log_3', FILENAME = N'/var/opt/mssql/log/fg_raymigrator_log_3.ldf' , SIZE = 131072KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

COLLATE Latin1_General_CI_AS
WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Frontend] SET COMPATIBILITY_LEVEL = 160
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Frontend].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
SET ANSI_NULL_DFLT_ON ON
GO
ALTER DATABASE [Frontend] SET ANSI_NULLS ON
GO
ALTER DATABASE [Frontend] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Frontend] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Frontend] SET ARITHABORT OFF 
GO
ALTER DATABASE [Frontend] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Frontend] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Frontend] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Frontend] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Frontend] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Frontend] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Frontend] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Frontend] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Frontend] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Frontend] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Frontend] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Frontend] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Frontend] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Frontend] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Frontend] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Frontend] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Frontend] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Frontend] SET RECOVERY FULL 
GO
ALTER DATABASE [Frontend] SET  MULTI_USER 
GO
ALTER DATABASE [Frontend] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Frontend] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Frontend] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Frontend] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Frontend] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Frontend] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Frontend', N'ON'
GO
ALTER DATABASE [Frontend] SET QUERY_STORE = ON
GO
ALTER DATABASE [Frontend] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
