/*
[RayMigrator]
Description = "Create table tablea"
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablea (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    value INT NULL,
    CONSTRAINT pk_tablea PRIMARY KEY (id)
);
