/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tableb (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label VARCHAR(100) NOT NULL,
    score INT NULL,
    CONSTRAINT pk_tableb PRIMARY KEY (id)
);
