/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tablex3 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ref VARCHAR(50) NOT NULL,
    data TEXT NULL,
    CONSTRAINT pk_tablex3 PRIMARY KEY (id)
);
