/*
[RayMigrator]
Environments = ["*"]
RunAlways = false
*/

CREATE TABLE tabley3 (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag VARCHAR(50) NOT NULL,
    priority INT NULL,
    CONSTRAINT pk_tabley3 PRIMARY KEY (id)
);
