/*
[RayMigrator]
Description = "Create TableD"
*/

CREATE TABLE tabled (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tabled PRIMARY KEY (id)
);
