/*
[RayMigrator]
Description = "Create TableC"
*/

CREATE TABLE tablec (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300) NULL,
    CONSTRAINT pk_tablec PRIMARY KEY (id)
);
